[package]
name = "arrow-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "5"
arrow = { version = "5" }
tokio = { version = "1", features = ["rt", "macros"] }
